language:
- python
python:
- '3.6'
- '2.7'
install:
- pip install -r requirements.txt
script: nosetests
deploy:
  provider: heroku
  api_key:
    secure: aQ9jN4JCpES1I/ZVR9wxZbrRn7W8niBMYieI1ww2fEX90a6Cv3/iowR24NID75CGJJdlmJqf1lEVsEXzQoL1l7tLickd2uHmRGqGTwo8cSrOI39+1NsUqaO9k4yr2vIIq6HObcT2fqoQA3yazLU4e+xX0tCO8u3OGVKO01WaJn8mhmLJuJes/3t+OKIC43LrJDUPdxkcTWXS4OhCgZVcjBrgNv6oJpOt5wiVscy4cCcoODn4cUfuKtAyCvY/XjmqpjySnHUh7M45YAg3NcA9AC+owIPMV3fD4AcU4CPipLJsFcG+hulam9otfE3XyG+KDgSLMZkHRmycKq8NVm1xDjKM7VANGjt88xrIjO7XuQsOGfdjFH70+w27WC7Rr/xSgNmGnqZFuMsH2zR22k/lFUatlSNAT5Dbf9UawP4AT/a4ho5zNdOs4NRFqkMShtOh7Sj6cPXF04uw49oApI/mkTf/UAVBb+UDH0IMo02gU0Bm4rqJncE1p1x89l5MFDhhR5pgcivURUhLQ58GyTX2JrLeddBMHLKId2+vcz39zRblqtEv1J7gvZKuFNu+e+jeMF8hr2rJcj+KfVOqTLGhKGXY/5Ah7D9oS0HbXoPFcg4L0Wd1vlkD17s6CBXUAPQ1o51UWbcL1a3FxklCaIMV3fQlG5I03Tp9r7rlKoTO48E=
  app: warm-everglades-64513
  on:
    repo: tfrench15/flaskrtaskr
